### ISSUE TITLE
Error with colors and plugin

### ISSUE THREAD

**Issue by MarcFerrerVWGS** [google/automotive-design-compose#1034] opened 2024-04-24 09:05 UTC
After getting the last update from live update and fetching the document we are having an error about the colors and it shutdowns the application. 
We didn't update the version of the design compose so the only thing remains is maybe something regarding the plugin and the new version. The previous versions works all fine.
So this error is from one day to another and we don't change anything on figma document.
This is the error we are getting:
![image](https://github.com/google/automotive-design-compose/assets/156323011/4ecdf3ae-5a3e-47a7-871d-8d06eb15e026)

**Comment by iamralpht** [comment] 2024-04-25 22:26
This looks like a duplicate of #1035 which we just merged a fix for and released 0.26.1 with the fix. We think this is a temporary regression in Figma's API responses, so with our fix, DesignCompose won't cause a crash (some errors will be logged) but gradient backgrounds might be missing. We noticed that editing the gradient in Figma causes the API to report all of the color values again.

**Closed** 2024-04-25 22:28 UTC
