### ISSUE TITLE
Unknown Figma Connection failure in embedded environment

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#96] opened 2023-05-31 21:30 UTC
Specifically Android Automotive OS, where multiple users can be logged in.

Bug: Even when you switch back to a user that had the token set already, the token was "lost", and you need to set the token again

**Comment by iamralpht** [comment] 2023-06-07 20:56
Aspirational for 0.21; not clear how much of a blocker this is for partners (Favorites might be higher priority)

**Comment by timothyfroehlich** [comment] 2023-06-08 16:59
High priority

**Comment by timothyfroehlich** [comment] 2023-06-14 20:21
@urpatil I've just tried to reproduce it on an emulator ( running system-images;android-32;android-automotive-playstore;x86_64) but couldn't get it to "lose" the token. I'll need more info here, starting with the system image (or at least API level) and reproduction steps.

I did find one issue that prevented setting the token using the Gradle task on multi-user systems, and I'm fixing that in #124 . I'm also including the rough script I wrote to test live update.

**Comment by iamralpht** [comment] 2023-06-15 18:46
Repros on Trout UDC, per @urpatil

**Comment by timothyfroehlich** [comment] 2023-06-21 20:58
Awaiting setup instructions for a Trout UDC build from @urpatil

**Comment by iamralpht** [comment] 2023-06-29 18:17
moving to next release since @timothyfroehlich doesn't have a repro setup (and 0.21 cut-off for changes is tomorrow).

**Comment by iamralpht** [comment] 2023-07-05 20:25
This is hard to reproduce, and might be because of poor error messages during no connectivity.

**Closed** 2023-07-19 20:28 UTC
Labels: bug, 👀 eyes, qol, :blue_square:  P3

**Comment by timothyfroehlich** [comment] 2023-07-19 20:31
Further investigation has shown that this is a networking issue caused by the host that results in all network connectivity failing. Closing this.
