### ISSUE TITLE
Squoosh: animation: individual timeline control

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#950] opened 2024-04-02 21:15 UTC
We'd like to have control over how individual elements that are animated in a transition move, and specify all transitions between different variants of components.

Currently, we have an automatically generated transition in squoosh that goes between all states, and will add some very basic transition control in 0.26, but this isn't sufficient to create most of the sample animations that we want to be able to achieve.

**Comment by rylin8** [comment] 2024-12-12 05:42
Dupe of https://github.com/google/automotive-design-compose/issues/1567

**Closed by rylin8** 2024-12-12 05:42 UTC
Labels: Type: New Feature, :green_circle:  P2, animation
