### ISSUE TITLE
[0.28.0+] Live Update is only available to users with a Figma Enterprise plan

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#1351] opened 2024-07-11 13:57 UTC
Design Compose 0.28 added support for [Figma Variables](https://help.figma.com/hc/en-us/articles/15339657135383-Guide-to-variables-in-Figma). This support depends on using Figma's REST API to fetch Variable information. Unfortunately, access to Variables form the REST API requires a [Figma Enterprise](https://www.figma.com/pricing/#features) account:

<img width="1542" alt="image" src="https://github.com/google/automotive-design-compose/assets/5819722/c9dcb6b3-d568-450a-b2b0-53b2478f5077">

This has had the unintentional consequence of making DesignCompose's Live Update service only available to users with the Figma Enterprise plan.

We're working on deciding what to do, but in the mean time users without an Enterprise plan will have to stick with DesignCompose version. 0.27.0.

Note: If you have an Enterprise plan and you are still getting sync errors then you may need to replace your Figma API key with one that includes read access for Variables. See #1296.

**Comment by rylin8** [comment] 2024-07-17 05:31
Dupe of https://github.com/google/automotive-design-compose/issues/1296 which has been fixed.

**Closed by rylin8** 2024-07-17 05:31 UTC
Labels: :exclamation::exclamation::exclamation:  P0

**Comment by timothyfroehlich** [comment] 2025-01-14 16:36
We've since made a change to fall back to default values when a user doesn't have access to the figma variables (such as if they don't have enterprise), so Figma Enterprise isn't required any more, only if you intend to use Figma's variables.

(Also, your comment implies that you think that a user of an app that's created with DesignCompose needs a Figma account. Users would only need an account to get live updates from the Figma document, but note that Live Update is only meant to be used while developing the app. Once the app is ready to be published and installed for users the developer is expected to disable Live Update)
