### ISSUE TITLE
Support offline updates: using `fetch` on a workstation and updating the device via `adb`

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#114] opened 2023-06-08 15:01 UTC
Not all test benches are connected to the internet (even via proxy), so we need to have clear instructions on an offline update flow. @timothyfroehlich I think there's a path that works currently (via `fetch` and `adb push`), but I don't think we've documented it -- probably super nice if we had a gradle task to do it, but I'm not sure how feasible that would be.

**Comment by timothyfroehlich** [comment] 2023-06-08 17:56
Awaiting design consensus in [go/designcompose-gradle-plugin-greendoc](https://goto.google.com/designcompose-gradle-plugin-greendoc)

**Comment by timothyfroehlich** [comment] 2023-06-08 17:59
@iamralpht is this a straight dupe of #75 or is there more to this request than what's in #75?

**Comment by iamralpht** [comment] 2023-06-08 22:27
@timothyfroehlich the only difference here is documenting how to update a design for configs where network permissions prevent live update; it could be via adb push or via re-installing the whole app.

**Closed** 2023-08-09 20:29 UTC
Labels: needs design, 👀 eyes, :green_circle:  P2
